# Generated by Django 4.0.1 on 2023-03-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Широта')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Местонахождение',
                'verbose_name_plural': 'Местонахождения',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Никнейм')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('member', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Админ')], max_length=9)),
                ('age', models.PositiveSmallIntegerField()),
                ('location', models.ManyToManyField(to='users.Location')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
